.Dd August 25, 2019
.Dt LUX 1
.Os
.Sh NAME
.Nm lux
.Nd package manager
.Sh SYNOPSIS
.Nm
.Op Fl LNR
.Cm command
.Ar package ...
.Sh DESCRIPTION
.Nm
executes
.Ar command
for each
.Ar package .
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl L
Use local database for interaction.
.It Fl N
Use absolute path for interaction.
.It Fl R
Use remote database for interaction.
.El
.Pp
.Ss Commands:
.Bl -tag -width show-description
.It Cm add
Install an exploded local package.
.It Cm del
Remove a local package.
.It Cm explode
Inflate and extract a remote package from cache.
.It Cm fetch
Fetch remote package to the cache.
.It Cm register
Register a remote package to the local database.
.It Cm populate-chksum
Populate the checksum file.
.It Cm populate-remote
Populate remote database.
.It Cm show-description
Write description from local package to the standard output.
.It Cm show-files
Write files from local package to the standard output.
to the standard output.
.It Cm show-license
Write license from local package to the standard output.
.It Cm show-mdeps
Write construction dependencies from local package
to the standard output.
.It Cm show-name
Write name from local package to the standard output.
.It Cm show-rdeps
Write real time dependencies from local package
to the standard output.
.It Cm show-version
Write version from local package to the standard output.
.It Cm unregister
Unregister a package from local database.
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr pkg_dbfile 5
