.Dd February 2018
.Dt LUX 1
.Os
.Sh NAME
.Nm lux
.Nd a package manager
.Sh SYNOPSIS
.Nm
.Op Fl L | N | R
.Cm add
.Ar package ...
.Nm
.Op Fl L | N | R
.Cm del
.Ar package ...
.Nm
.Op Fl L | N | R
.Cm explode
.Ar package ...
.Nm
.Op Fl L | N | R
.Cm fetch
.Ar package ...
.Nm
.Op Fl L | N | R
.Cm info
.Op Fl adfmpr
.Ar package
