#define PKG_DIR "/"
#define PKG_BIN "/bin"
#define PKG_ETC "/etc/format"
#define PKG_LDB "/var/pkg/local"
#define PKG_RDB "/var/pkg/remote"
#define PKG_TMP "/var/pkg/cache"

#define PKG_SRC "url"
#define PKG_FMT ".tar.gz"
#define PKG_SIG ".sig"
